rbac:
  roles:
    # App-based roles instead of traditional roles
    MTLS-APP:
      - "/service-a/**"
      - "/service-b/**"
      - "/user-service/**"
      - "/order-service/**"
    MTLS2-APP:
      - "/service-b/**"
      - "/user-service/profile/**"
    PAYMENT-APP:
      - "/payment-service/**"
      - "/user-service/billing/**"
    FRONTEND-APP:
      - "/service-b/**"
      - "/public/**"
  
  certificates:
    # External clients (different issuer/subject pattern)
    mtls: MTLS-APP                    # External app
    mtls2: MTLS2-APP                  # External app  
    frontend: FRONTEND-APP            # External frontend
    
    # Internal services (internal issuer/subject pattern)
    service-a.internal: SERVICE-A     # Internal service
    service-b.internal: SERVICE-B     # Internal service
    payment.internal: PAYMENT-SERVICE # Internal service
  
  # Public endpoints that don't require certificates
  public-endpoints:
    - "/public/**"
    - "/health/**"
    - "/info/**"
  
  # Internal service-to-service communication (bypass gateway)
  internal-services:
    SERVICE-A:
      - "SERVICE-B"
      - "USER-SERVICE"
    SERVICE-B:
      - "PAYMENT-SERVICE"
    PAYMENT-SERVICE:
      - "USER-SERVICE"