rbac:
  # Certificate CN to role mapping
  certificates:
    mtls: "mtls-client"
    mtls2: "mtls2-client"

  # Role-based permissions
  roles:
    mtls-client:
      - "/service-a/**"
      - "/service-b/**"
    mtls2-client:
  #   - "/service-a/**"
      - "/service-b/response"

  # Public endpoints (no authentication required)
  public-endpoints:
    - "/actuator/health"
    - "/actuator/info"

